 
# 常用重码字：
# 原为二码：已xsu，个xol，义xik，庆xxik，头xyk，达xxyk，午xoj，并xtt，内xob，业xtc，汉xee，欠xno，飞xxno，尹xsk，杀xkd，苗xtw，叉xei，术xid，宋xjd，乜xpn，灭xmf，扎xqu，尘xfg，勺xpi，艾xtk，
# 原为三码：气xomn，点xyrf，板xdhe，淮xeog，梨xhnd，贡xmbo，憩xhup，针xopj，压xmgi，炯xfbr，荣xtbd，恐xmnp，慰xsip，怂xoop，柒xepd，奥xhbk，弥xnof，亟xnem，伛xosk，殳xhne，熬xxqkf，
# 原为四码：遗xylmo，脱xbcru，悦xpcru，玫xmgok，贱xboij，萝xtwln，毫xyrbu，观xebhu，嘉xgrtr，绒xvmij，换xqnbk，唤xrnbk，晾xayrf，掀xqhlo，贷xopbo，敌xhrok，扁xisbt，郑xtknl，滚xeycv，亏xmmvs，诣xivpa，捨xqomr，啥xromr，晖xabkq，洒xemcw，歉xtcno，遥xybou，萤xtbli，蔣xtvmi，
# 原为五码：税xhdcr，瑶xmgbo，随xnlyk，顽xmumb，
#
#           通过按 Shift + Enter可以上屏转换后的编码

patch:
  
#允許在光標位置獲取失敗時於窗口左上角繪製候選框（而不是桌面左上角）  
  style/layout/enhanced_position: true
#字频调整
  translator/enable_user_dict: false
#碼表輸入法連打
  translator/enable_sentence: true
#關閉倉頡與拼音混打
  abc_segmentor/extra_tags: {}
#顶字上屏
  speller/auto_select: false
  
#調整字根展示方式
  translator/preedit_format: 
#「字根在前（$1），字母在後（\U$1\E）」「([a-z]*)后面加了$是大写字母」
#    - xform/^([a-z]*)/$1/ 
#    - xform/^([a-z]*)/\U$1\E | $1/
    - xform/^([a-z]*)/$1/
    - "xlit|日月金木水火土竹戈十大中一弓人心手口尸廿山女田難卜符|abcdefghijklmnopqrstuvwxyz|"
  translator/comment_format:
#   字母在後，提示顯示爲字根
    - xlit|abcdefghijklmnopqrstuvwxyz~|日月金木水火土竹戈十大中一弓人心手口尸廿山女田難卜符~|
  
#以下兩行爲去除朙月拼音依赖
  "reverse_lookup/dictionary": {}
  "schema/dependencies": {}

#以下兩行爲輸入Symbols修正，修正後按「/」才能調出符號
  "punctuator/import_preset": symbols
  "recognizer/patterns/punct": "^/([a-z]+|[0-9])$"

#加入常用符號
  punctuator/symbols:
#常用符號/物理
    '/wuli': [ °, °C, Ω, Φ, m², cm², km², m³ ]
#常用符號/數學
    '/uuxt': [ ±, ×, ÷, ≤, ≥, ≠, ≈, ∞, ✓, x]
#几何
    '/jihe': [ ◄, ►, ▲, ▼]
#箭頭
    '/jmtz': [ ←, →, ↑, ↓, ↖, ↗, ↙, ↘]
#商標
    '/uhbn': [ ®, ™]
    
#Shift鍵切換中英文
  ascii_composer/switch_key:
#    Control_L: inline_ascii
#   Control_R: inline_ascii
    Shift_L: inline_ascii
    Shift_R: inline_ascii
     

#標點符號顶字上屏
  key_binder/bindings:
    - { when: has_menu, accept: comma, send: comma } #逗号
    - { when: has_menu, accept: period, send: period } #句号
    - { accept: "Shift+space", toggle: noop, when: always} #取消全半角切换

#中文, 半角, 中文標點, 繁體漢字, 通用字集
  switches:
    - name: ascii_mode
      reset: 0
      states: ["中文", "西文"]
    - name: full_shape
      reset: 0
      states: ["半角", "全角"]
    - name: ascii_punct
      reset: 0
      states: ["，。", "，．"]
    - name: simplification
      reset: 0
      states: ["漢字", "汉字"]
    - name: extended_charset
      reset: 1
      states: ["通用", "增廣"]
