 
# 常用重码字：
# 原为一码：1字
  #  曰xa
# 原为二码：31字
  #  已xsu，个xol，义xik，庆xxik，头xyk，达xxyk，午xoj，并xtt，内xob，业xtc，
  #  汉xee，欠xno，飞xxno，尹xsk，杀xkd，苗xtw，叉xei，术xid，宋xjd，灭xmf，
  #  扎xqu，尘xfg，勺xpi，艾xtk，旨xpa，仑xop，夷xkn，杠xdm，弘xni，乜xpn，
  #  芈xtq，
# 原为三码：24字
  #  气xomn，点xyrf，板xdhe，淮xeog，冗xbhn，奥xhbk，贡xmbo，针xopj，压xmgi，荣xtbd，
  #  迸xytt，恐xmnp，娄xfdv，慰xsip，怂xoop，梨xhnd，佑xokr，秉xhdl，坠xnog，歼xmnhj，
  #  憩xhup，炯xfbr，憨xnkp，亟xnem，
# 原为四码：40字
  #  观xebhu，贪xoino，遗xylmo，贷xopbo，敌xhrok，玫xmgok，贱xboij，绒xvmij，劫xgiks，萝xtwln，
  #  毫xyrbu，嘉xgrtr，掀xqhlo，扁xisbt，郑xtknl，亏xmmvs，诣xivpa，歉xtcno，邵xsrnl，砍xmrno，
  #  换xqnbk，唤xrnbk，脱xbcru，悦xpcru，晾xayrf，晖xabkq，遥xybou，摇xqbou，滚xeycv，啥xromr，
  #  洒xemcw，萤xtbli，敝xfbok，涩xesim，钩xoppi，忾xpomn，蛊xlibt，攒xqhuo，噜xrnwa，俪xombb，
  #  

#
# 常用符号：
# 天气'/tq'，几何'/jh'，数字+圈'/szq'，字母+圈'/zmq'，漢字+圈'/hzq'，

patch:
  
#允許在光標位置獲取失敗時於窗口左上角繪製候選框（而不是桌面左上角）  
  style/layout/enhanced_position: true
#字频调整
  translator/enable_user_dict: false
#碼表輸入法連打
  translator/enable_sentence: true
#關閉倉頡與拼音混打
  abc_segmentor/extra_tags: {}
#顶字上屏
  speller/auto_select: false
  
#調整字根展示方式
  translator/preedit_format: 
#「字根在前（$1），字母在後（\U$1\E）」「([a-z]*)后面加了$是大写字母」
#    - xform/^([a-z]*)/$1/ 
#    - xform/^([a-z]*)/\U$1\E | $1/
    - xform/^([a-z]*)/$1/
    - "xlit|日月金木水火土竹戈十大中一弓人心手口尸廿山女田難卜符|abcdefghijklmnopqrstuvwxyz|"
  translator/comment_format:
#   字母在後，提示顯示爲字根
    - xlit|abcdefghijklmnopqrstuvwxyz~|日月金木水火土竹戈十大中一弓人心手口尸廿山女田難卜符~|
  
#以下兩行爲去除朙月拼音依赖
  "reverse_lookup/dictionary": {}
  "schema/dependencies": {}

#以下兩行爲輸入Symbols修正，修正後按「/」才能調出符號
  "punctuator/import_preset": symbols
  "recognizer/patterns/punct": "^/([a-z]+|[0-9])$"

#加入常用符號
  punctuator/symbols:
#常用符號/物理
    '/wuli': [ °, °C, Ω, Φ, m², cm², km², m³ ]
#常用符號/數學
    '/uuxt': [ ±, ×, ÷, ≤, ≥, ≠, ≈, ∞, ✓, x]
#常用符號/几何
    '/jihe': [ ◄, ►, ▲, ▼]
#常用符號/箭頭
    '/jmtz': [ ↑, ↓, ←, →, ↕, ↔, ↖, ↗, ↙, ↘]
#常用符號/商標
    '/uhbn': [ ®, ™]
#常用符號/逻辑学
    '/loji': [ ¬, ∧, ∨, →, ↔, ⊥, ｜, ↓, ├, ∴, ∵, ⊃, ⇒, ⇔, ⊕, ⊻, ∀, ∃, ≡]
    
#Shift鍵切換中英文
  ascii_composer/switch_key:
#    Control_L: inline_ascii
#   Control_R: inline_ascii
    Shift_L: inline_ascii
    Shift_R: inline_ascii
     

#標點符號顶字上屏
  key_binder/bindings:
    - { when: has_menu, accept: comma, send: comma } #逗号
    - { when: has_menu, accept: period, send: period } #句号
    - { accept: "Shift+space", toggle: noop, when: always} #取消全半角切换

#中文, 半角, 中文標點, 繁體漢字, 通用字集
  switches:
    - name: ascii_mode
      reset: 0
      states: ["中文", "西文"]
    - name: full_shape
      reset: 0
      states: ["半角", "全角"]
    - name: ascii_punct
      reset: 0
      states: ["，。", "，．"]
    - name: simplification
      reset: 0
      states: ["漢字", "汉字"]
    - name: extended_charset
      reset: 1
      states: ["通用", "增廣"]
